### PR TITLE
added numkeys functionality

### PR DESCRIPTION
**Pull request by kulicuu**
http://redis.io/commands/eval

Redis eval protocol might have changed a bit since your last commit.
The first argument (after the script itself) should be the number of keys following.  
So this works with current version. (~2.8)

### CODE REVIEW

**Comment by ChrisRus** [comment]
All is not well, Travis. 5 of 8 tests fail with this patch applied. Going to take a closer look at this tomorrow.

**Comment by kulicuu** [comment]
Interesting.
I'm looking at a Green checkmark with "All is well -- The Travis CI build passed - Details" right above this comment.  ('above' when I was composing it, below when it's posted)
I assume that's an automatic test run by GitHub ? 
And you are running your own tests on your machine ?  
And what version of Redis are you using ?

**Comment by kulicuu** [comment]
Okay I actually took a closer look at @arunoda code and understand it better.  
My pull request is redundant and irrelevant because having the `[keys.length].concat` line already has the numkeys argument in it to begin with.  
However, if you fail to pass an empty array for the situation of no keys arguments then it will pass undefined to the Redis eval command, which may or may not be a problem.

**Comment by arunoda** [comment]
Thanks for the PR and the fix.
Merging.

**Comment by kulicuu** [comment]
ah cool thx.

**Comment by ChrisRus** [comment]
Just getting back on this. Thanks for the updates. Going to try them out immediately.

**Comment by ChrisRus** [comment]
Latest is working well for me. 

FWIW, I'm testing with a local clone of the package with redis client dependency updated to ^0.10.1 (same as my other components).

Thanks to both of you. Chris

**Pull request merged**
